"""add notification_modes to user

Revision ID: 26da9b6b3902
Revises: 7795a347af29
Create Date: 2026-02-09 19:04:32.380764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26da9b6b3902'
down_revision: Union[str, Sequence[str], None] = '7795a347af29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('users', sa.Column('notification_modes', sa.JSON(), nullable=True))
    
    # 2. Update existing rows with default value ["email"]
    # En PostgreSQL, on utilise json_build_array ou on passe une chaîne JSON
    op.execute("UPDATE users SET notification_modes = '[\"email\"]' WHERE notification_modes IS NULL")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('users', 'notification_modes', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_modes')
    # ### end Alembic commands ###
