"""Add latitude and longitude nullable

Revision ID: 32c83a7b9f48
Revises: 8697d384a20a
Create Date: 2026-01-15 16:48:32.477149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c83a7b9f48'
down_revision: Union[str, Sequence[str], None] = '8697d384a20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capteurs', 'parcelle_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('localites', 'altitude')
    op.add_column('terrains', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('terrains', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terrains', 'longitude')
    op.drop_column('terrains', 'latitude')
    op.add_column('localites', sa.Column('altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('capteurs', 'parcelle_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
