"""Cleanup: Remove non-compliant tables and fix relations

Revision ID: 6d641a4f8fb2
Revises: e17f8e136377
Create Date: 2025-12-11 16:23:46.479782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d641a4f8fb2'
down_revision: Union[str, Sequence[str], None] = 'e17f8e136377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. D'abord, supprimer les relations vers les tables à supprimer
    op.add_column('historique_cultures', sa.Column('culture_nom', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_historique_cultures_culture_id'), table_name='historique_cultures')
    op.drop_constraint('historique_cultures_culture_id_fkey', 'historique_cultures', type_='foreignkey')
    op.drop_column('historique_cultures', 'culture_id')

    op.add_column('parcelles', sa.Column('culture_actuelle', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_parcelles_culture_actuelle_id'), table_name='parcelles')
    op.drop_constraint('parcelles_culture_actuelle_id_fkey', 'parcelles', type_='foreignkey')
    op.drop_column('parcelles', 'culture_actuelle_id')

    # 2. Ensuite, supprimer les tables non conformes
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_parcelle_id'), table_name='alerts')
    op.drop_table('alerts')

    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_table('predictions')

    op.drop_index(op.f('ix_cultures_id'), table_name='cultures')
    op.drop_index(op.f('ix_cultures_nom'), table_name='cultures')
    op.drop_table('cultures')

    # 3. Enfin, ajouter les nouvelles colonnes
    op.add_column('recommendations', sa.Column('expert_metadata', sa.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'recommendations', 'users', ['user_id'], ['id'])
    op.add_column('sensor_measurements', sa.Column('parcelle_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'sensor_measurements', 'parcelles', ['parcelle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_measurements', type_='foreignkey')
    op.drop_column('sensor_measurements', 'parcelle_id')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_column('recommendations', 'user_id')
    op.drop_column('recommendations', 'expert_metadata')
    op.add_column('parcelles', sa.Column('culture_actuelle_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('parcelles_culture_actuelle_id_fkey'), 'parcelles', 'cultures', ['culture_actuelle_id'], ['id'])
    op.create_index(op.f('ix_parcelles_culture_actuelle_id'), 'parcelles', ['culture_actuelle_id'], unique=False)
    op.drop_column('parcelles', 'culture_actuelle')
    op.add_column('historique_cultures', sa.Column('culture_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('historique_cultures_culture_id_fkey'), 'historique_cultures', 'cultures', ['culture_id'], ['id'])
    op.create_index(op.f('ix_historique_cultures_culture_id'), 'historique_cultures', ['culture_id'], unique=False)
    op.drop_column('historique_cultures', 'culture_nom')
    op.create_table('predictions',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('modele', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resultat', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('date_prediction', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('predictions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('niveau', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_declenchement', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('est_resolue', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parcelle_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parcelle_id'], ['parcelles.id'], name=op.f('alerts_parcelle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_parcelle_id'), 'alerts', ['parcelle_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('cultures',
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type_culture', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cultures_pkey'))
    )
    op.create_index(op.f('ix_cultures_nom'), 'cultures', ['nom'], unique=True)
    op.create_index(op.f('ix_cultures_id'), 'cultures', ['id'], unique=False)
    # ### end Alembic commands ###
