"""add superficie to terrain

Revision ID: 7795a347af29
Revises: 7e02cef1c465
Create Date: 2026-02-09 17:52:35.269891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7795a347af29'
down_revision: Union[str, Sequence[str], None] = '7e02cef1c465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capteurs', 'dev_eui',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_index(op.f('ix_capteurs_parcelle_id'), table_name='capteurs')
    op.drop_constraint(op.f('capteurs_parcelle_id_fkey'), 'capteurs', type_='foreignkey')
    op.drop_column('capteurs', 'parcelle_id')
    op.add_column('terrains', sa.Column('superficie', sa.Float(), nullable=True))
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('terrains', 'superficie')
    op.add_column('capteurs', sa.Column('parcelle_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('capteurs_parcelle_id_fkey'), 'capteurs', 'parcelles', ['parcelle_id'], ['id'])
    op.create_index(op.f('ix_capteurs_parcelle_id'), 'capteurs', ['parcelle_id'], unique=False)
    op.alter_column('capteurs', 'dev_eui',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
