"""add code to capteurs

Revision ID: 77b4d753e970
Revises: 6d641a4f8fb2
Create Date: 2025-12-24 08:28:10.399357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77b4d753e970'
down_revision: Union[str, Sequence[str], None] = '6d641a4f8fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # On définit les valeurs possibles pour climatezone
    climate_zone_enum = sa.Enum('TROPICAL', 'SUBTROPICAL', 'TEMPERATE', 'CONTINENTAL', 'ARID', 'SEMI_ARID', 'MEDITERRANEAN', name='climatezone')
    climate_zone_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capteurs', sa.Column('code', sa.String(length=200), nullable=False))
    op.add_column('capteurs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_capteurs_code'), 'capteurs', ['code'], unique=False)
    op.add_column('historique_cultures', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('historique_cultures', 'culture_nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('localites', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('localites', sa.Column('population', sa.Float(), nullable=True))
    op.add_column('localites', sa.Column('climate_zone', sa.Enum('TROPICAL', 'SUBTROPICAL', 'TEMPERATE', 'CONTINENTAL', 'ARID', 'SEMI_ARID', 'MEDITERRANEAN', name='climatezone'), nullable=True))
    op.add_column('localites', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('parcelles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('parcelles', 'type_sol',
               existing_type=postgresql.ENUM('ARGILEUX', 'SABLEUX', 'LIMONEUX', 'HUMIFERE', 'CALCAIRE', 'TOURBEUX', name='typesol'),
               nullable=True)
    op.add_column('recommendations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('recommendations', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('sensor_measurements', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('sensor_measurements', 'parcelle_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('terrains', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('terrains', 'deleted_at')
    op.alter_column('sensor_measurements', 'parcelle_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('sensor_measurements', 'deleted_at')
    op.alter_column('recommendations', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('recommendations', 'deleted_at')
    op.alter_column('parcelles', 'type_sol',
               existing_type=postgresql.ENUM('ARGILEUX', 'SABLEUX', 'LIMONEUX', 'HUMIFERE', 'CALCAIRE', 'TOURBEUX', name='typesol'),
               nullable=False)
    op.drop_column('parcelles', 'deleted_at')
    op.drop_column('localites', 'deleted_at')
    op.drop_column('localites', 'climate_zone')
    op.drop_column('localites', 'population')
    op.drop_column('localites', 'altitude')
    op.alter_column('historique_cultures', 'culture_nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('historique_cultures', 'deleted_at')
    op.drop_index(op.f('ix_capteurs_code'), table_name='capteurs')
    op.drop_column('capteurs', 'deleted_at')
    op.drop_column('capteurs', 'code')
    sa.Enum(name='climatezone').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
