"""simplify schema and add cap_parcelle

Revision ID: 7e02cef1c465
Revises: 235c09cd5340
Create Date: 2026-01-16 21:59:43.004017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e02cef1c465'
down_revision: Union[str, Sequence[str], None] = '235c09cd5340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cap_parcelles',
    sa.Column('capteur_id', sa.String(length=36), nullable=False),
    sa.Column('parcelle_id', sa.String(length=36), nullable=False),
    sa.Column('date_assignation', sa.DateTime(), nullable=False),
    sa.Column('date_desassignation', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capteur_id'], ['capteurs.id'], ),
    sa.ForeignKeyConstraint(['parcelle_id'], ['parcelles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cap_parcelles_capteur_id'), 'cap_parcelles', ['capteur_id'], unique=False)
    op.create_index(op.f('ix_cap_parcelles_id'), 'cap_parcelles', ['id'], unique=False)
    op.create_index(op.f('ix_cap_parcelles_parcelle_id'), 'cap_parcelles', ['parcelle_id'], unique=False)
    op.drop_column('localites', 'code_postal')
    op.drop_column('localites', 'timezone')
    op.drop_column('localites', 'longitude')
    op.drop_column('localites', 'population')
    op.drop_column('localites', 'quartier')
    op.drop_column('localites', 'superficie')
    op.drop_column('localites', 'latitude')
    op.drop_column('parcelles', 'date_recolte_estimee')
    op.drop_column('parcelles', 'systeme_irrigation')
    op.drop_column('parcelles', 'source_eau')
    op.drop_column('parcelles', 'date_plantation')
    op.drop_column('parcelles', 'culture_actuelle')
    op.drop_column('parcelles', 'statut')
    op.drop_column('parcelles', 'type_sol')
    op.drop_column('terrains', 'superficie_totale')
    op.drop_column('terrains', 'longitude')
    op.drop_column('terrains', 'type_terrain')
    op.drop_column('terrains', 'date_acquisition')
    op.drop_column('terrains', 'latitude')
    op.drop_column('terrains', 'pente')
    op.drop_column('terrains', 'statut')
    op.drop_column('terrains', 'perimetre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terrains', sa.Column('perimetre', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('statut', postgresql.ENUM('ACTIF', 'EN_JACHERE', 'EN_PREPARATION', 'ABANDONNE', name='statutterrain'), autoincrement=False, nullable=False))
    op.add_column('terrains', sa.Column('pente', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('date_acquisition', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('type_terrain', postgresql.ENUM('AGRICOLE', 'PASTORAL', 'MIXTE', 'EXPERIMENTAL', name='typeterrain'), autoincrement=False, nullable=False))
    op.add_column('terrains', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('superficie_totale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('parcelles', sa.Column('type_sol', postgresql.ENUM('ARGILEUX', 'SABLEUX', 'LIMONEUX', 'HUMIFERE', 'CALCAIRE', 'TOURBEUX', name='typesol'), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('statut', postgresql.ENUM('ACTIVE', 'EN_CULTURE', 'EN_JACHERE', 'EN_PREPARATION', 'RECOLTE_EN_COURS', name='statutparcelle'), autoincrement=False, nullable=False))
    op.add_column('parcelles', sa.Column('culture_actuelle', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('date_plantation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('source_eau', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('systeme_irrigation', postgresql.ENUM('GOUTTE_A_GOUTTE', 'ASPERSION', 'GRAVITAIRE', 'PIVOT', 'AUCUN', name='systemeirrigation'), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('date_recolte_estimee', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('superficie', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('localites', sa.Column('quartier', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('population', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('code_postal', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cap_parcelles_parcelle_id'), table_name='cap_parcelles')
    op.drop_index(op.f('ix_cap_parcelles_id'), table_name='cap_parcelles')
    op.drop_index(op.f('ix_cap_parcelles_capteur_id'), table_name='cap_parcelles')
    op.drop_table('cap_parcelles')
    # ### end Alembic commands ###
