"""add statut to capteurs

Revision ID: 8697d384a20a
Revises: 77b4d753e970
Create Date: 2025-12-24 08:55:28.771270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8697d384a20a'
down_revision: Union[str, Sequence[str], None] = '77b4d753e970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capteurs', sa.Column('statut', sa.Enum('actif', 'inactif', 'maintenance', 'erreur', name='statutcapteur'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capteurs', 'statut')
    # ### end Alembic commands ###
