"""add recommendation_frequency to user

Revision ID: 989a5058327f
Revises: 26da9b6b3902
Create Date: 2026-02-09 19:45:29.524804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989a5058327f'
down_revision: Union[str, Sequence[str], None] = '26da9b6b3902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create the enum type manually if needed (Alembic usually does this automatically but safer to check)
    # However, op.add_column with sa.Enum usually handles it.
    
    # 2. Add column as nullable first
    op.add_column('users', sa.Column('recommendation_frequency', sa.Enum('WEEKLY', 'MONTHLY', 'QUARTERLY', 'DISABLED', name='recommendationfrequency'), nullable=True))
    
    # 3. Update existing rows with default value 'WEEKLY'
    op.execute("UPDATE users SET recommendation_frequency = 'WEEKLY' WHERE recommendation_frequency IS NULL")
    
    # 4. Alter column to be NOT NULL
    op.alter_column('users', 'recommendation_frequency', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recommendation_frequency')
    # ### end Alembic commands ###
