"""Initial schema with correct UUID foreign keys

Revision ID: e17f8e136377
Revises: 
Create Date: 2025-11-29 14:37:41.722556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17f8e136377'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultures',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_culture', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultures_id'), 'cultures', ['id'], unique=False)
    op.create_index(op.f('ix_cultures_nom'), 'cultures', ['nom'], unique=True)
    op.create_table('localites',
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('quartier', sa.String(length=200), nullable=True),
    sa.Column('ville', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.Column('continent', sa.Enum('AFRIQUE', 'AMERIQUE_NORD', 'AMERIQUE_SUD', 'ASIE', 'EUROPE', 'OCEANIE', 'ANTARCTIQUE', name='continent'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('superficie', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localites_id'), 'localites', ['id'], unique=False)
    op.create_index(op.f('ix_localites_nom'), 'localites', ['nom'], unique=False)
    op.create_index(op.f('ix_localites_pays'), 'localites', ['pays'], unique=False)
    op.create_index(op.f('ix_localites_ville'), 'localites', ['ville'], unique=False)
    op.create_table('users',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', name='userstatus'), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=False),
    sa.Column('dernier_acces', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('resultat', sa.JSON(), nullable=False),
    sa.Column('date_prediction', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('terrains',
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('type_terrain', sa.Enum('AGRICOLE', 'PASTORAL', 'MIXTE', 'EXPERIMENTAL', name='typeterrain'), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'EN_JACHERE', 'EN_PREPARATION', 'ABANDONNE', name='statutterrain'), nullable=False),
    sa.Column('localite_id', sa.String(length=36), nullable=False),
    sa.Column('superficie_totale', sa.Float(), nullable=False),
    sa.Column('perimetre', sa.Float(), nullable=True),
    sa.Column('altitude_moyenne', sa.Float(), nullable=True),
    sa.Column('pente', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date_acquisition', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['localite_id'], ['localites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terrains_id'), 'terrains', ['id'], unique=False)
    op.create_index(op.f('ix_terrains_localite_id'), 'terrains', ['localite_id'], unique=False)
    op.create_index(op.f('ix_terrains_nom'), 'terrains', ['nom'], unique=False)
    op.create_index(op.f('ix_terrains_user_id'), 'terrains', ['user_id'], unique=False)
    op.create_table('parcelles',
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('terrain_id', sa.String(length=36), nullable=False),
    sa.Column('superficie', sa.Float(), nullable=False),
    sa.Column('type_sol', sa.Enum('ARGILEUX', 'SABLEUX', 'LIMONEUX', 'HUMIFERE', 'CALCAIRE', 'TOURBEUX', name='typesol'), nullable=False),
    sa.Column('statut', sa.Enum('ACTIVE', 'EN_CULTURE', 'EN_JACHERE', 'EN_PREPARATION', 'RECOLTE_EN_COURS', name='statutparcelle'), nullable=False),
    sa.Column('culture_actuelle_id', sa.String(length=36), nullable=True),
    sa.Column('date_plantation', sa.DateTime(), nullable=True),
    sa.Column('date_recolte_estimee', sa.DateTime(), nullable=True),
    sa.Column('systeme_irrigation', sa.Enum('GOUTTE_A_GOUTTE', 'ASPERSION', 'GRAVITAIRE', 'PIVOT', 'AUCUN', name='systemeirrigation'), nullable=True),
    sa.Column('source_eau', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['culture_actuelle_id'], ['cultures.id'], ),
    sa.ForeignKeyConstraint(['terrain_id'], ['terrains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelles_code'), 'parcelles', ['code'], unique=True)
    op.create_index(op.f('ix_parcelles_culture_actuelle_id'), 'parcelles', ['culture_actuelle_id'], unique=False)
    op.create_index(op.f('ix_parcelles_id'), 'parcelles', ['id'], unique=False)
    op.create_index(op.f('ix_parcelles_nom'), 'parcelles', ['nom'], unique=False)
    op.create_index(op.f('ix_parcelles_terrain_id'), 'parcelles', ['terrain_id'], unique=False)
    op.create_table('alerts',
    sa.Column('niveau', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_declenchement', sa.DateTime(), nullable=False),
    sa.Column('est_resolue', sa.Boolean(), nullable=False),
    sa.Column('parcelle_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcelle_id'], ['parcelles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_parcelle_id'), 'alerts', ['parcelle_id'], unique=False)
    op.create_table('capteurs',
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('dev_eui', sa.String(length=16), nullable=False),
    sa.Column('parcelle_id', sa.String(length=36), nullable=False),
    sa.Column('date_installation', sa.DateTime(), nullable=False),
    sa.Column('date_activation', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcelle_id'], ['parcelles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capteurs_dev_eui'), 'capteurs', ['dev_eui'], unique=True)
    op.create_index(op.f('ix_capteurs_id'), 'capteurs', ['id'], unique=False)
    op.create_index(op.f('ix_capteurs_nom'), 'capteurs', ['nom'], unique=False)
    op.create_index(op.f('ix_capteurs_parcelle_id'), 'capteurs', ['parcelle_id'], unique=False)
    op.create_table('historique_cultures',
    sa.Column('parcelle_id', sa.String(length=36), nullable=False),
    sa.Column('culture_id', sa.String(length=36), nullable=False),
    sa.Column('date_plantation', sa.DateTime(), nullable=False),
    sa.Column('date_recolte', sa.DateTime(), nullable=True),
    sa.Column('rendement', sa.Float(), nullable=True),
    sa.Column('qualite', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['culture_id'], ['cultures.id'], ),
    sa.ForeignKeyConstraint(['parcelle_id'], ['parcelles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historique_cultures_culture_id'), 'historique_cultures', ['culture_id'], unique=False)
    op.create_index(op.f('ix_historique_cultures_id'), 'historique_cultures', ['id'], unique=False)
    op.create_index(op.f('ix_historique_cultures_parcelle_id'), 'historique_cultures', ['parcelle_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('priorite', sa.String(), nullable=False),
    sa.Column('date_emission', sa.DateTime(), nullable=False),
    sa.Column('parcelle_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcelle_id'], ['parcelles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_parcelle_id'), 'recommendations', ['parcelle_id'], unique=False)
    op.create_table('sensor_measurements',
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('azote', sa.Float(), nullable=True),
    sa.Column('phosphore', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('capteur_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capteur_id'], ['capteurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_measurements_capteur_id'), 'sensor_measurements', ['capteur_id'], unique=False)
    op.create_index(op.f('ix_sensor_measurements_id'), 'sensor_measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_measurements_id'), table_name='sensor_measurements')
    op.drop_index(op.f('ix_sensor_measurements_capteur_id'), table_name='sensor_measurements')
    op.drop_table('sensor_measurements')
    op.drop_index(op.f('ix_recommendations_parcelle_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_historique_cultures_parcelle_id'), table_name='historique_cultures')
    op.drop_index(op.f('ix_historique_cultures_id'), table_name='historique_cultures')
    op.drop_index(op.f('ix_historique_cultures_culture_id'), table_name='historique_cultures')
    op.drop_table('historique_cultures')
    op.drop_index(op.f('ix_capteurs_parcelle_id'), table_name='capteurs')
    op.drop_index(op.f('ix_capteurs_nom'), table_name='capteurs')
    op.drop_index(op.f('ix_capteurs_id'), table_name='capteurs')
    op.drop_index(op.f('ix_capteurs_dev_eui'), table_name='capteurs')
    op.drop_table('capteurs')
    op.drop_index(op.f('ix_alerts_parcelle_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_parcelles_terrain_id'), table_name='parcelles')
    op.drop_index(op.f('ix_parcelles_nom'), table_name='parcelles')
    op.drop_index(op.f('ix_parcelles_id'), table_name='parcelles')
    op.drop_index(op.f('ix_parcelles_culture_actuelle_id'), table_name='parcelles')
    op.drop_index(op.f('ix_parcelles_code'), table_name='parcelles')
    op.drop_table('parcelles')
    op.drop_index(op.f('ix_terrains_user_id'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_nom'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_localite_id'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_id'), table_name='terrains')
    op.drop_table('terrains')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_localites_ville'), table_name='localites')
    op.drop_index(op.f('ix_localites_pays'), table_name='localites')
    op.drop_index(op.f('ix_localites_nom'), table_name='localites')
    op.drop_index(op.f('ix_localites_id'), table_name='localites')
    op.drop_table('localites')
    op.drop_index(op.f('ix_cultures_nom'), table_name='cultures')
    op.drop_index(op.f('ix_cultures_id'), table_name='cultures')
    op.drop_table('cultures')
    # ### end Alembic commands ###
