"""add cap_parcelle and update sensor plot relationship

Revision ID: e6b78fcf7e0b
Revises: 235c09cd5340
Create Date: 2026-01-16 17:58:26.475836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6b78fcf7e0b'
down_revision: Union[str, Sequence[str], None] = '235c09cd5340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capteurs', 'dev_eui',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_index(op.f('ix_capteurs_parcelle_id'), table_name='capteurs')
    op.drop_constraint(op.f('capteurs_parcelle_id_fkey'), 'capteurs', type_='foreignkey')
    op.drop_column('capteurs', 'parcelle_id')
    op.drop_column('localites', 'population')
    op.drop_column('localites', 'timezone')
    op.drop_column('localites', 'code_postal')
    op.drop_column('localites', 'longitude')
    op.drop_column('localites', 'latitude')
    op.drop_column('localites', 'superficie')
    op.drop_column('localites', 'quartier')
    op.drop_column('parcelles', 'culture_actuelle')
    op.drop_column('parcelles', 'date_recolte_estimee')
    op.drop_column('parcelles', 'type_sol')
    op.drop_column('parcelles', 'source_eau')
    op.drop_column('parcelles', 'date_plantation')
    op.drop_column('parcelles', 'statut')
    op.drop_column('parcelles', 'systeme_irrigation')
    op.drop_column('terrains', 'pente')
    op.drop_column('terrains', 'superficie_totale')
    op.drop_column('terrains', 'longitude')
    op.drop_column('terrains', 'type_terrain')
    op.drop_column('terrains', 'statut')
    op.drop_column('terrains', 'perimetre')
    op.drop_column('terrains', 'latitude')
    op.drop_column('terrains', 'date_acquisition')
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('date_acquisition', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('perimetre', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('statut', postgresql.ENUM('ACTIF', 'EN_JACHERE', 'EN_PREPARATION', 'ABANDONNE', name='statutterrain'), autoincrement=False, nullable=False))
    op.add_column('terrains', sa.Column('type_terrain', postgresql.ENUM('AGRICOLE', 'PASTORAL', 'MIXTE', 'EXPERIMENTAL', name='typeterrain'), autoincrement=False, nullable=False))
    op.add_column('terrains', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('terrains', sa.Column('superficie_totale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('terrains', sa.Column('pente', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('systeme_irrigation', postgresql.ENUM('GOUTTE_A_GOUTTE', 'ASPERSION', 'GRAVITAIRE', 'PIVOT', 'AUCUN', name='systemeirrigation'), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('statut', postgresql.ENUM('ACTIVE', 'EN_CULTURE', 'EN_JACHERE', 'EN_PREPARATION', 'RECOLTE_EN_COURS', name='statutparcelle'), autoincrement=False, nullable=False))
    op.add_column('parcelles', sa.Column('date_plantation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('source_eau', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('type_sol', postgresql.ENUM('ARGILEUX', 'SABLEUX', 'LIMONEUX', 'HUMIFERE', 'CALCAIRE', 'TOURBEUX', name='typesol'), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('date_recolte_estimee', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('parcelles', sa.Column('culture_actuelle', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('quartier', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('superficie', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('localites', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('code_postal', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('localites', sa.Column('population', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('capteurs', sa.Column('parcelle_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('capteurs_parcelle_id_fkey'), 'capteurs', 'parcelles', ['parcelle_id'], ['id'])
    op.create_index(op.f('ix_capteurs_parcelle_id'), 'capteurs', ['parcelle_id'], unique=False)
    op.alter_column('capteurs', 'dev_eui',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
